# Generated by Django 4.2.4 on 2023-10-05 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_chat_staff_chat_staff_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
