# Generated by Django 4.2.4 on 2023-09-14 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_alter_orderitem_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='favoriteproduct',
            name='user_id',
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
