# Generated by Django 4.2.4 on 2023-09-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_product_id_favoriteproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproduct',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20),
        ),
    ]
