# Generated by Django 4.2.4 on 2023-09-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_favoriteproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображений'},
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('brown', 'Brown'), ('yellow', 'Yellow'), ('black', 'Black'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('white', 'White')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=5, null=True),
        ),
    ]
