# Generated by Django 4.2.4 on 2023-09-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Карзина', 'verbose_name_plural': 'Товары в Корзине'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Элемент Карзина', 'verbose_name_plural': 'Элементы Корзины'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
