# Generated by Django 4.2.4 on 2023-09-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('коричневый', 'Коричневый'), ('желтый', 'Желтый'), ('черный', 'Черный'), ('красный', 'Красный'), ('синий', 'Синий'), ('зеленый', 'Зеленый'), ('розовый', 'Розовый'), ('белый', 'Белый')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
