# Generated by Django 4.2.4 on 2023-09-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_color_size_delete_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Обработка', 'Обработка'), ('В пути', 'В пути'), ('Доставлено', 'Доставлено')], default='Обработка', max_length=20),
        ),
    ]
