# Generated by Django 4.2.4 on 2023-09-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_cartitem_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total_price',
            new_name='total',
        ),
    ]
