# Generated by Django 4.2.4 on 2023-09-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_rename_total_price_cartitem_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Новый Заказ', 'Новый Заказ'), ('Обработка', 'Обработка'), ('В пути', 'В пути'), ('Доставлено', 'Доставлено')], default='Обработка', max_length=20),
        ),
    ]
