# Generated by Django 4.2.4 on 2023-09-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_shippingoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingoption',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipping Cost'),
        ),
    ]
