# Generated by Django 4.2.4 on 2023-09-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_shippingoption_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orders_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
