# Generated by Django 4.2.4 on 2023-09-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_orders_orders_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipping_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.shippingoption'),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
