# Generated by Django 4.2.4 on 2023-09-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_orders_shipping_option_orders_total_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total_price',
        ),
    ]
