# Generated by Django 4.2.4 on 2023-09-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Новый Заказ', 'Новый Заказ'), ('Обработка', 'Обработка'), ('В пути', 'В пути'), ('Доставлено', 'Доставлено')], default='Новый Заказ', max_length=20),
        ),
    ]
